version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: ./producer
    container_name: event_producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    volumes:
      - ./producer:/app
    ports:
      - "4000:4000"

  analytics:
    build: ./analytics
    container_name: analytics_consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    volumes:
      - ./analytics:/app
    ports:
      - "3000:3000"

  notifications:
    build: ./notifications
    container_name: notifications_consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    volumes:
      - ./notifications:/app
    ports:
      - "5000:5000"
