version: '3.8'

services:
  analytics:
    build: ./analytics
    container_name: analytics_consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: 192.168.1.15:9092
    volumes:
      - ./analytics:/app
    ports:
      - "3000:3000"

  notifications:
    build: ./notifications
    container_name: notifications_consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: 192.168.1.15:9092
    volumes:
      - ./notifications:/app
    ports:
      - "5000:5000"
